# Generated by Django 5.2.10 on 2026-04-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_alter_tag_unique_together_place_classification_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='ledger.category'),
        ),
    ]
