# Generated by Django 5.2.12 on 2026-05-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='resigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
