# Generated by Django 5.2.12 on 2026-05-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_verified_at_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_savings',
            field=models.BooleanField(default=False),
        ),
    ]
