# Generated by Django 5.2.10 on 2026-04-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='recurringtransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'ordering': ['-created_at']},
        ),
    ]
