# Generated by Django 5.2.10 on 2026-04-03 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_category_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
