# Generated by Codex on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='transaction_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='categories',
                to='ledger.transactiontype',
            ),
        ),
    ]
