# Generated by Django 5.2.10 on 2026-04-13 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_alter_category_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='place',
            name='classification',
            field=models.CharField(blank=True, help_text='Town, City, Village, Online', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='classification',
            field=models.CharField(blank=True, help_text='DIY, Restaurant, Supermarket, Online', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(help_text='HEMA, IKEA, Online', max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Groceries, Entertainment, Online', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(help_text='Debit, Credit, Transfer (for accounts)', max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('created_by', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('name', 'classification')},
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('name', 'classification')},
        ),
    ]
