# Generated by Django 5.2.10 on 2026-04-16 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_alter_tag_unique_together_place_classification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transactionlog',
            name='ledger_tran_transac_182dde_idx',
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(help_text='Woerden, Utrecht, Online', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(help_text='HEMA, IKEA, Online', max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['transaction', '-created_at'], name='ledger_tran_transac_699809_idx'),
        ),
    ]
