# Generated by Django 5.2.10 on 2026-04-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_remove_transactionlog_ledger_tran_transac_182dde_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='store',
            name='classification',
            field=models.CharField(blank=True, help_text='Diy, Restaurant, Supermarket, Online', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(help_text='Hema, Ikea, Online', max_length=255, unique=True),
        ),
    ]
