# Generated by Django 5.2.12 on 2026-06-04 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_accountlog'),
        ('users', '0005_account_is_savings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountlog',
            new_name='ledger_acco_account_30b40d_idx',
            old_name='ledger_acco_account_8dcb52_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='pair_transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='pair_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pair_transactions', to='users.account'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='ledger.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='users.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
